# Generated by Django 4.2 on 2024-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('studentsenrolled', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=100)),
                ('instructorfullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentInformation',
            new_name='StudentInfo',
        ),
    ]
