# Generated by Django 4.2 on 2024-04-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_courseinfo_rename_studentinformation_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
    ]
