# Generated by Django 4.2 on 2024-04-23 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollmentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentinfo',
            old_name='studentname',
            new_name='firsttname',
        ),
        migrations.AddField(
            model_name='enrollmentinfo',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
