# Generated by Django 4.2 on 2024-04-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_rename_firsttname_enrollmentinfo_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentinfo',
            old_name='firstname',
            new_name='studentname',
        ),
        migrations.RemoveField(
            model_name='enrollmentinfo',
            name='lastname',
        ),
    ]
